ARG LOOM_BASE_IMAGE
FROM ${LOOM_BASE_IMAGE}

RUN set -eux; \
    apt-get update; \
    apt-get install --yes --no-install-recommends git; \
    rm -rf /var/lib/apt/lists/*

ENV MAVEN_CONFIG=/tmp/.m2

WORKDIR /workspace

CMD ["mvn"]
