ARG LOOM_SOURCE_IMAGE
ARG LOOM_BASE_IMAGE
FROM ${LOOM_SOURCE_IMAGE} AS wordpress-source

FROM ${LOOM_BASE_IMAGE}

COPY --from=wordpress-source /usr/src/wordpress /usr/src/wordpress
COPY docker-entrypoint-wordpress /usr/local/bin/docker-entrypoint-wordpress

ENTRYPOINT ["docker-entrypoint-wordpress"]
CMD ["apache2-foreground"]
