version: 1
name: loom-db-mongodb
runtime:
  engine: podman
  rootless: true
  machine:
    managed: true
services:
  db:
    type: mongodb
    image: ${MONGO_IMAGE:-ghcr.io/loom-development/mongo-7.0@sha256:406a4fdca9fc763443268f000218d3849ef8996f66ed9e92ba0b501b446ab822}
    env:
      MONGO_INITDB_ROOT_USERNAME: loom
      MONGO_INITDB_ROOT_PASSWORD: loom
      MONGO_INITDB_DATABASE: loom
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongodb:/data/db
